name: Main CI

on:
  push:
    branches:
    - mbedtls

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          pwd && ls -la builder
#          cd builder && mkdir dev && ln -s /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00224843-e298-0022-4843-e29800224843/net/eth0 /home/runner/work/docker/docker/builder/dev/eth0 && pwd && ls -la /home/runner/work/docker/docker/builder/dev/eth0

      - name: dockerize
        run: |
          docker network prune && docker network create b-net && docker network ls && docker inspect b-net
          pwd && cd builder && ls -la && docker build . -t mbedtls:v1
          perl scripts/plif.pl && ip address show
          docker image ls mbedtls:v1
          docker run --rm -t mbedtls:v1
#          echo PARAMETERS DEFAULT CONTAINER RUN
#          echo STARTED WITH docker run --rm -t httpd_ssl:v1
#          docker run --rm -t httpd_ssl:v1
#          echo PARAMETERS IP CONTAINER RUN
#          echo STARTED WITH docker run --rm -t pnscan:v1 45.33.32.156 20:30
#          docker run --rm -t pnscan:v1 45.33.32.156 20:30
#          echo PARAMETERS HOSTNAME CONTAINER RUN
#          echo STARTED WITH docker run --rm -t pnscan:v1 scanme.nmap.org 20:30
#          docker run --rm -t pnscan:v1 scanme.nmap.org 20:30
