name: Main CI

on:
  push:
    branches:
    - stud

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: dockerize
        run: |
          cd builder && docker build . -t stud:v1
          docker image ls stud:v1
          docker run --rm -t stud:v1
#          echo PARAMETERS DEFAULT CONTAINER RUN
#          echo STARTED WITH docker run --rm -t httpd_ssl:v1
#          docker run --rm -t httpd_ssl:v1
#          echo PARAMETERS IP CONTAINER RUN
#          echo STARTED WITH docker run --rm -t pnscan:v1 45.33.32.156 20:30
#          docker run --rm -t pnscan:v1 45.33.32.156 20:30
#          echo PARAMETERS HOSTNAME CONTAINER RUN
#          echo STARTED WITH docker run --rm -t pnscan:v1 scanme.nmap.org 20:30
#          docker run --rm -t pnscan:v1 scanme.nmap.org 20:30
